# Generated by Django 4.0.5 on 2022-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_FIO', models.CharField(max_length=100)),
                ('employees_age', models.CharField(max_length=100)),
            ],
        ),
    ]
