# Generated by Django 4.0.5 on 2022-06-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='employees_Models',
        ),
        migrations.RenameField(
            model_name='employees_models',
            old_name='employees_FIO',
            new_name='employees_Models_FIO',
        ),
        migrations.RenameField(
            model_name='employees_models',
            old_name='employees_age',
            new_name='employees_Models_age',
        ),
    ]
