# Generated by Django 4.0.5 on 2022-06-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employees_employees_models_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees_models',
            name='employees_Models_FIO',
        ),
        migrations.AddField(
            model_name='employees_models',
            name='employees_Models_FirstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees_models',
            name='employees_Models_LastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees_models',
            name='employees_Models_MidleName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employees_models',
            name='employees_Models_age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
