# Generated by Django 4.0.5 on 2022-06-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employees_models_employees_models_fio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_models',
            name='employees_Models_job',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
