# Generated by Django 4.0.5 on 2022-06-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employees_models_employees_models_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_models',
            name='employees_Models_age',
            field=models.PositiveSmallIntegerField(blank=True, max_length=2),
        ),
    ]
