# Generated by Django 4.0.5 on 2022-06-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employees_models_employees_models_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees_models',
            name='employees_Models_FirstName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employees_models',
            name='employees_Models_LastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employees_models',
            name='employees_Models_MidleName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employees_models',
            name='employees_Models_job',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
