# Generated by Django 4.0.5 on 2022-06-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_category', models.CharField(max_length=100)),
                ('emplayees_FIO', models.CharField(max_length=100)),
                ('emplayees_age', models.CharField(max_length=100)),
            ],
        ),
    ]
