# Generated by Django 4.0.5 on 2022-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_FIO', models.CharField(max_length=100)),
                ('employees_age', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='emplayees_FIO',
        ),
        migrations.RemoveField(
            model_name='job',
            name='emplayees_age',
        ),
    ]
