# Generated by Django 4.0.5 on 2022-06-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_employees_remove_job_emplayees_fio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
    ]
